apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: springpet-clinic
  labels:
    app: springpet-application
spec:
  path: /
  to:
    kind: Service
    name: springpet-clinic
    weight: 100
  port:
    targetPort: my-http