apiVersion: v1
kind: Service
metadata:
  name: springpet-clinic
  labels:
    app: springpet-application
spec:
  type: ClusterIP
  ports:
    - name: my-http
      port: 8080
      targetPort: 8080
  selector:
    app: springpet-application